spring:
  application:
    name: playground
  datasource:
    url: jdbc:h2:file:./db/h2;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
  sql:
    init:
      mode: never
  jooq:
    sql-dialect: h2
server:
  port: 8080
logging:
  level:
    org:
      jooq: INFO
