spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1; # In memory DB
    driverClassName: org.h2.Driver
    username: 'sa'
    password: ''
  flyway:
    enabled: true
  sql:
    init:
      mode: never
  jooq:
    sql-dialect: H2
server:
  port: 0 # Use port 0 to assign a random free port (required for @LocalServerPort)
